### ISSUE TITLE
运行报错KeyError: 'dhn'

### ISSUE THREAD

**Issue by cqulwq** [bcmi/SLBR-Visible-Watermark-Removal#15]
运行的时候报错，是原因呢。
Traceback (most recent call last):
  File "D:/kuaipan/caiji/DL_github/SLBR-Visible-Watermark-Removal-master/test.py", line 180, in <module>
    main(parser.parse_args())
  File "D:/kuaipan/caiji/DL_github/SLBR-Visible-Watermark-Removal-master/test.py", line 85, in main
    Machine = models.__dict__[args.models](datasets=data_loaders, args=args)
  File "D:\kuaipan\caiji\DL_github\SLBR-Visible-Watermark-Removal-master\src\models\__init__.py", line 7, in basic
    return BasicModel(**kwargs)
  File "D:\kuaipan\caiji\DL_github\SLBR-Visible-Watermark-Removal-master\src\models\BasicModel.py", line 35, in __init__
    self.model = nets.__dict__[self.args.nets](args=args)
KeyError: 'dhn'
==> creating model 

进程已结束,退出代码1

**Comment by jimleungjing** [comment]
参考scripts/test.sh 的参数
